### ISSUE TITLE
`windrun` cannot be calculated from LOOP packets

### ISSUE THREAD

**Issue by tkeffer** [chaunceygardiner/weewx-loopdata#8]
Because LOOP packets do not have an `interval` field, they cannot calculate `windrun`. This causes a `weewx.CannotCalculate` exception to be raised.

This patch should fix the problem (NOT TESTED):

```python
Index: bin/user/loopdata.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/bin/user/loopdata.py b/bin/user/loopdata.py
--- a/bin/user/loopdata.py	(revision 0ee9d2ba94c53888154363aa412f1d5d5002ff12)
+++ b/bin/user/loopdata.py	(revision 9839bb2bd58f547658c5d8fe25a69f14f192837a)
@@ -807,11 +807,14 @@
                 pkt_time: int       = to_int(pkt['dateTime'])
                 pkt['interval']     = self.cfg.loop_frequency / 60.0
 
-                windrun_val = weewx.wxxtypes.WXXTypes.calc_windrun('windrun', pkt)
-                pkt['windrun'] = windrun_val[0]
-                if windrun_val[0] > 0.00 and 'windDir' in pkt and pkt['windDir'] is not None:
-                    bkt = LoopProcessor.get_windrun_bucket(pkt['windDir'])
-                    pkt['windrun_%s' % windrun_bucket_suffixes[bkt]] = windrun_val[0]
+                try:
+                    windrun_val = weewx.wxxtypes.WXXTypes.calc_windrun('windrun', pkt)
+                    pkt['windrun'] = windrun_val[0]
+                    if windrun_val[0] > 0.00 and 'windDir' in pkt and pkt['windDir'] is not None:
+                        bkt = LoopProcessor.get_windrun_bucket(pkt['windDir'])
+                        pkt['windrun_%s' % windrun_bucket_suffixes[bkt]] = windrun_val[0]
+                except weewx.CannotCalculate:
+                    pass
 
                 beaufort_val = weewx.wxxtypes.WXXTypes.calc_beaufort('beaufort', pkt)
                 pkt['beaufort'] = beaufort_val[0]
```

**Comment by chaunceygardiner** [comment]
My reply copied here from my reply on weewx-users:
Thanks, Tom.

I don’t think that’s the problem as I add an interval to the (copy of) the packet.  That is needed because I keep my own set of accumulators so that loopdata can write out observations on every loop packet (in its own thread) and never have to access the database.  I can add an interval because the user specifies a LoopFrequency in seconds.

Indeed, on my VantagePro2 and RainWise weewx installs, I have no problem with windrun in loopdata.

I’ve seen issues at startup when I’ve tried the WeatherLinkUDP driver and I have code not checked in to catch and ignore errors to make it pass the startup, but I worry that loopdata won’t be accurate for drivers where loop packets don’t always contain all the data.  It’s not something I am likely to tackle anytime soon.

I’m guessing this driver is one of those cases, where loops don’t contain all the observations.  If so, it’s not a good candidate to use loopdata (at least, not at this time).

To the original OP, does everything work fine without loopdata?  Furthermore, does loopdata break the operation of weewx?  I’d be surprised if this is true as the loopdata thread should just die.

**Comment by chaunceygardiner** [comment]
I updated the README to specify what drivers this extension has been tested with. Also, to mention that this extension expects all observations on every loop packet.

Notwithstanding the above, I now check for windrun (and Beaufort) exceptions when calculating.
